#ifndef JUDGER_PTRACE_FIX_H
#define JUDGER_PTRACE_FIX_H

#ifdef __APPLE__

#define PTRACE_TRACEME PT_TRACE_ME
#define PTRACE_KILL PT_KILL
#define PTRACE_CONT PT_CONTINUE
#define PTRACE_SYSCALL PT_CONTINUE

#endif

#endif //JUDGER_PTRACE_FIX_H
